// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lktxfhtvxygsigealzif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrdHhmaHR2eHlnc2lnZWFsemlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTcwNjQsImV4cCI6MjA2NTQ3MzA2NH0.z9cEDipmxYm_hTGaI3Al1A4MlCC2OKMSvRY4ARpIGtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);